name: Update Monkeytype 30-Second Personal Best
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC (5:30 AM IST)
  workflow_dispatch: # Allows manual trigger
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run script
        env:
          APE_KEY: ${{ secrets.APE_KEY }}
        run: node update-readme.js
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update Monkeytype 30-second personal best" || echo "No changes to commit"
          git push
